# -*- coding: utf-8 -*-
"""primeiro_passo.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pUUJoAM_b2Tyvo2szORYji31VkdVEwN5
"""

#-*- coding: utf-8 -*-

print('olá mundo')

var1 = 45
var2 = 32
var3 = True
print (var3)

print (var1 + var2)

if (var1 > var2 and var3 == True):
  print ( str(var1) + " é maior que " + str(var2))