# -*- coding: utf-8 -*-
"""primeiro_passo.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pUUJoAM_b2Tyvo2szORYji31VkdVEwN5
"""

#-*- coding: utf-8 -*-
#variaveis

print('olá mundo')

var1 = 45
var2 = 32
var3 = True
print (var3)

print (var1 + var2)

if (var1 > var2 and var3 == True):
  print ( str(var1) + " é maior que " + str(var2))

#listas
nova_lista=["bolo", "pudim", "pave", "sagu", 3 ]
sobremesa=["sorvete", "bolono pote", "caviar"]

def imprimir_lista(menu):
  print(menu)

imprimir_lista(nova_lista)

nova_lista[4] = "torta"
imprimir_lista(nova_lista)

del nova_lista[4] 
imprimir_lista(nova_lista)

nova_lista.reverse()
imprimir_lista(nova_lista)

nova_lista.remove("bolo")
imprimir_lista(nova_lista)

menu_completo=[nova_lista + sobremesa]
imprimir_lista(menu_completo)
print ("############################")

for comida in nova_lista:
  print(comida)

#dicionarios
dados_cadrastro = {"nome" :"ray", "cep" :48404488, "bairro": "Valparaiso"}
dados_cadrastro